name: Run Unit Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2.4.0
        with:
          java-version: '11'
          distribution: 'temurin'   # Use 'temurin' or 'adoptopenjdk' instead of 'openjdk'
          java-package: 'jdk'
          architecture: 'x64'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test
